#!/bin/bash

VERSION_FILE="version.txt"
if [ ! -f "$VERSION_FILE" ]; then
    echo "1.0.0.0.0.0" > "$VERSION_FILE"
fi

CURRENT_VERSION=$(cat "$VERSION_FILE")
IFS='.' read -r -a VERSION_PARTS <<< "$CURRENT_VERSION"

# Increment the dev version
VERSION_PARTS[5]=$((VERSION_PARTS[5] + 1))

NEW_VERSION="${VERSION_PARTS[0]}.${VERSION_PARTS[1]}.${VERSION_PARTS[2]}.${VERSION_PARTS[3]}.${VERSION_PARTS[4]}.${VERSION_PARTS[5]}"
echo "$NEW_VERSION" > "$VERSION_FILE"
echo "$NEW_VERSION"
